# #####################################################
#
#   PHP CLI setup with Xdebug
#
# #####################################################

FROM php:7.2.9

RUN apt-get update \
 && apt-get install -y git zip unzip zlib1g-dev mysql-client \
 && docker-php-ext-install zip \
 && docker-php-ext-install pdo_mysql \
 && docker-php-ext-install bcmath \
 && docker-php-ext-install sockets \
 && curl -sS https://getcomposer.org/installer \
  | php -- --install-dir=/usr/local/bin --filename=composer

RUN pecl install -o -f redis \
    && pecl install xdebug-2.6.0 \
    && rm -rf /tmp/pear \
    && docker-php-ext-enable redis xdebug

COPY ./auto/php/php.ini /usr/local/etc/php/

WORKDIR /usr/src

COPY ./composer.json .
COPY ./composer.lock .
COPY ./phpcs.xml .
COPY ./phpunit.xml.dist .

RUN mkdir -p /usr/src/data/cache

RUN /usr/local/bin/composer install --no-interaction  \
    && /usr/local/bin/composer dump-autoload -o


