# #####################################################
#
#   PHP CLI setup with Xdebug
#
# #####################################################

FROM php:7.2.9

RUN apt-get update \
 && apt-get install -y git zlib1g-dev \
 && docker-php-ext-install zip \
 && docker-php-ext-install pdo_mysql \
 && curl -sS https://getcomposer.org/installer \
  | php -- --install-dir=/usr/local/bin --filename=composer

RUN pecl install -o -f redis \
    && pecl install xdebug-2.6.0 \
    && rm -rf /tmp/pear \
    && docker-php-ext-enable redis xdebug

ADD . /usr/src
COPY ./assets/php/php.ini /usr/local/etc/php/

EXPOSE 80

ENV APPLICATION_ENVIRONMENT development

ENV DB_HOST localhost
ENV DB_PORT 3306
ENV DB_NAME althingi
ENV DB_USER root
#ENV DB_PASSWORD

ENV SEARCH none


ENV CACHE_TYPE none
    # | file (path ./data/cache) | memory | none
ENV CACHE_HOST localhost
ENV CACHE_PORT 6379


WORKDIR /usr/src
