/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

ALTER TABLE `IssueLink` RENAME COLUMN `from_category` TO `from_kind`;
ALTER TABLE `IssueLink` RENAME COLUMN `to_category` TO `to_kind`;

/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
