<?php
/**
 * Created by PhpStorm.
 * User: einarvalur
 * Date: 20/05/15
 * Time: 7:40 AM
 */

namespace Althingi\Controller;

use Mockery;
use Zend\Test\PHPUnit\Controller\AbstractHttpControllerTestCase;

class CabinetControllerTest extends AbstractHttpControllerTestCase
{
    use ServiceHelper;

    public function setUp()
    {
        $this->setApplicationConfig(
            include __DIR__ .'/../application.config.php'
        );
        parent::setUp();
        $this->buildServices([
            'Althingi\Service\Congressman',
            'Althingi\Service\Party',
            'Althingi\Service\Cabinet',
        ]);
    }

    public function tearDown()
    {
        \Mockery::close();
        $this->destroyServices();
        return parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function testGet()
    {
        $this->getMockService('Althingi\Service\Cabinet')
            ->shouldReceive('fetchByAssembly')
            ->andReturn([(object)['cabinet_id' => 1]])
            ->getMock();

        $this->getMockService('Althingi\Service\Party')
            ->shouldReceive('getByCongressman')
            ->andReturn([(object)['party_id' => 1]])
            ->getMock();

        $this->getMockService('Althingi\Service\Congressman')
            ->shouldReceive('fetchByCabinet')
            ->andReturn([(object)['congressman_id' => 1, 'date'=> '2001-01-01']])
            ->getMock();

        $this->dispatch('/loggjafarthing/1/raduneyti', 'GET');

        $this->assertControllerClass('CabinetController');
        $this->assertActionName('assembly');
        $this->assertResponseStatusCode(200);
    }
}
