<?=$this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?=$this->headTitle('Althingi')->setSeparator(' - ')->setAutoEscape(false);?>
        <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,700' rel='stylesheet' type='text/css'>
        <?=$this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Scripts -->
        <?php echo $this->headScript()

        ; ?>
        <!-- Le styles -->
        <?=
            $this->headLink([
                'rel' => 'shortcut icon',
                'type' => 'image/vnd.microsoft.icon',
                'href' => $this->basePath('/img/favicon.ico')])
            ; ?>
        <style type="text/css">
            *, *:before, *:after {
                margin: 0;
                padding: 0;
                box-sizing: border-box;
            }
            body {
                width: 900px;
                padding: 30px;
                margin: auto;
                font-family: 'Open Sans', sans-serif;
                line-height: 1.33;
                color: rgb(100, 100, 100);
                font-weight: 400;
            }

            ul {
                list-style: inside disc;
            }

            h1, h2, h3, h4, h5, h6 {
                font-weight: 700;
            }

            pre {
                background-color: rgb(240,240,240);
            }

            article {
                padding: 30px 0;
                margin-bottom: 30px;
            }

            .docs__table ~ .docs__table {
                margin-top: 30px;
            }
            .docs__table ~ pre {
                margin-top: 30px;
            }
            .docs__table {
                width: 100%;
                border-collapse: collapse;
                border: 1px solid rgb(200, 200, 200);
            }
            .docs__table caption {
                margin-bottom: 7px;
                text-align: start;
            }
            .docs__table thead {
                background-color: rgb(240, 240, 240);
            }
            .docs__table thead td,
            .docs__table thead th {
                font-weight: 700;
            }
            .docs__table td,
            .docs__table th {
                padding: 4px;
                text-align: left;
                vertical-align: top;
            }

            .docs__parameters {
                width: 100%;
                border-collapse: collapse;
            }
            .docs__parameters td,
            .docs__parameters th {
                text-align: left;
            }


            nav[role=navigation] {}
            nav[role=navigation] ul {}
            nav[role=navigation] ul a {
                text-decoration: none;
                color: rgb(100, 100, 100);
            }

            .docs__header {
                padding: 15px 0;
            }

            .docs__method { }
            .docs__method p {
                margin: 7px 0;
            }
            .docs__method h4 {
                margin: 30px 0;
            }

            .docs__method h3 {
                padding: 7px 15px;
                margin: 15px 0;
            }

            .docs__method--GET h3 {
                background-color: #4CAF50;
                color: antiquewhite;
            }

            .docs__method--PUT h3 {
                background-color: #FF9800;
            }

            .docs__method--POST h3 {
                background-color: #FFC107;
            }
            .docs__method--PATCH h3 {
                background-color: #FFEB3B;
            }

            .docs__method--OPTIONS h3 {
                background-color: #c8ffbd;
            }
            .docs__method--DELETE h3 {
                background-color: #F44336;
                color: antiquewhite;
            }

        </style>

    </head>
    <body>
        <?php echo $this->content; ?>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
